import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { ReviewState } from "./types.js";

function section(title: string, body?: string): string {
  return `## ${title}\n\n${body?.trim() || "_No output produced._"}\n`;
}

function reviewModeLabel(reviewMode: string): string {
  return reviewMode === "diff" ? "Git diff review" : "Full repository review";
}

function diffSummarySection(state: ReviewState): string {
  if (state.context.reviewMode !== "diff") {
    return "";
  }

  return section("Diff Summary", state.context.diffSummary || "No changes were detected.");
}

export async function writeMarkdownReport(state: ReviewState): Promise<string> {
  const outputDir = path.resolve(process.cwd(), "output");
  await mkdir(outputDir, { recursive: true });

  const reportPath = path.join(outputDir, "code-review-report.md");
  const supervisorOutput = state.supervisorIterations
    .map((result, index) => `### Iteration ${index + 1}\n\n${result.output.trim()}`)
    .join("\n\n");

  const report = `# Agentic Code Review Report

Generated by the Agentic Code Review Orchestrator.

**Repository:** \`${state.context.repoPath}\`

**Review mode:** ${reviewModeLabel(state.context.reviewMode)}

**Supervisor accepted:** ${state.accepted ? "Yes" : "No"}

**Final decision:** ${state.finalDecision}

${diffSummarySection(state)}
${section("Review Plan", state.planner?.output)}
${section("Code Review", state.codeReview?.output)}
${section("Test Review", state.testReview?.output)}
${section("Fix Proposals", state.fixProposal?.output)}
${section("Supervisor Evaluation", supervisorOutput)}
## Orchestration Patterns Demonstrated

- Sequential workflow: planner, code reviewer, test reviewer, and fix proposer run in order.
- Parallel workflow: code review and test review run together after planning.
- Conditional branching: the supervisor can accept the result or request a refined fix proposal.
- Loop with max iterations: supervisor review runs up to ${state.context.maxSupervisorIterations} iteration(s).
- Supervisor pattern: the supervisor evaluates all agent outputs before the final report is written.
`;

  await writeFile(reportPath, report, "utf8");
  return reportPath;
}
